name: Build Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar CMake
        run: cmake -S . -B build

      - name: Compilar
        run: cmake --build build --config Release

      - name: Upload do build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
